/**
 * @fileoverview Preset configurations extracted from Storybook stories
 * @author svguitar-react
 * @version 1.0.0
 */

import type { Chord, ChordDiagramProps, Instrument, ViewId } from "../components/ChordDiagram/types";
import { DEFAULT_CHORD_STYLE } from "../components/ChordDiagram/constants";

export interface PresetConfig {
	id: string;
	name: string;
	description?: string;
	props: ChordDiagramProps;
}

// Base configuration with all defaults
const BASE_CONFIG = {
	...DEFAULT_CHORD_STYLE,
	tuningLabelOffsetX: 0.5,
	tuningLabelOffsetY: 0.5,
	tuningLabelFormat: "scientific" as const,
	stringIndicatorOffsetX: 0.5,
	stringIndicatorOffsetY: 0,
	barresWidth: 8,
	barresOpacity: 1,
	barresOffsetX: 0,
	barresOffsetY: 0,
	fretTextOffsetX: 0,
	fretTextOffsetY: 0,
	nutStrokeWidth: 0.075,
	nutOffsetX: 0,
	nutOffsetY: 0,
	nutOpacity: 1.0,
	nutColor: "#333333",
	canvasOffsetX: 0,
	canvasOffsetY: 0,
};

// Default tuning - same as used in all stories
const DEFAULT_TUNING = ["E2", "A2", "D3", "G3", "B3", "E4"];

export const CHORD_PRESETS: PresetConfig[] = [
	{
		id: "c-major-default",
		name: "Default",
		description: "C Major chord with default styling",
		props: {
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "x32010",
			},
			...BASE_CONFIG,
			view: "vertical-right",
			width: 128,
			height: 219,
			canvasOffsetX: -39,
			canvasOffsetY: -19,
			fretCount: 5,
			fretWidth: 19,
			stringWidth: 1,
			dotSize: 17,
			barreHeight: 9,
			fretTextColor: "#c6c6c6",
			fontFamily: "monospace",
			dotTextSize: 11,
			fretTextSize: 11,
			tuningTextSize: 16,
			fretHeight: 35,
			tuningTextColor: "#e0e0e0",
			tuningLabelFormat: "note-only",
			validation: "strict",
			invalidBehavior: "render-fallback",
			tuningLabelOffsetX: 0.01,
			tuningLabelOffsetY: 0.27,
			barresOffsetY: -0.11,
			stringIndicatorOffsetX: 0.58,
			stringIndicatorOffsetY: 0.63,
			fretTextOffsetX: -0.13,
			fretTextOffsetY: 0.11,
		},
	},
	{
		id: "f-major-with-barre-horizontal-right",
		name: "F Major (Horizontal Right)",
		description: "F Major chord with barre in horizontal layout",
		props: {
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "133211",
			},
			chord: {
				fingers: [],
				barres: [{ fret: 1, fromString: 1, toString: 6, text: "F" }],
			},
			...BASE_CONFIG,
			view: "horizontal-right",
			width: 535,
			height: 214,
			fretCount: 5,
			fretWidth: 47,
			fretHeight: 30,
			dotSize: 18,
			barreHeight: 19,
			backgroundColor: "#ffffff",
			fretColor: "#333333",
			stringColor: "#666666",
			fretTextColor: "#abaaaa",
			fontFamily: "sans-serif",
			dotTextSize: 15,
			fretTextSize: 17,
			tuningTextSize: 17,
			stringWidth: 1,
			barresWidth: 12,
			barresOffsetX: 0.37,
			barresOffsetY: -0.14,
			tuningTextColor: "#9e9a9a",
			tuningLabelOffsetX: 0.28,
			tuningLabelOffsetY: -0.04,
			tuningLabelFormat: "note-only",
			stringIndicatorOffsetY: 0,
			canvasOffsetX: 0,
			fretTextOffsetX: 0,
			fretTextOffsetY: 0,
			nutStrokeWidth: 0.075,
			nutColor: "#333333",
		},
	},
	{
		id: "f-major-with-barre-vertical-right",
		name: "F Major (Vertical Right)",
		description: "F Major chord with barre in vertical layout",
		props: {
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "133211",
			},
			chord: {
				fingers: [],
				barres: [{ fret: 1, fromString: 1, toString: 6, text: "F" }],
			},
			...BASE_CONFIG,
			view: "vertical-right",
			width: 192,
			height: 261,
			fretCount: 5,
			fretWidth: 23,
			fretHeight: 39,
			dotSize: 18,
			barreHeight: 10,
			fretTextColor: "#d1d0d0",
			fontFamily: "sans-serif",
			dotTextSize: 15,
			fretTextSize: 17,
			stringWidth: 1,
			barresWidth: 10,
			barresOffsetX: 0.12,
			barresOffsetY: 0.33,
			tuningTextColor: "#cecbcb",
			tuningLabelOffsetX: 0.04,
			tuningLabelOffsetY: 0.15,
			tuningLabelFormat: "note-only",
			stringIndicatorOffsetX: 0.35,
			fretTextOffsetX: -6.32,
			fretTextOffsetY: 0.16,
		},
	},
	{
		id: "with-fret-notation",
		name: "G Major (Fret Notation)",
		description: "G Major using fret notation",
		props: {
			instrument: {
				tuning: ["E2", "A2", "D3", "G3", "B3", "E4"],
				chord: "320003",
			},
			...BASE_CONFIG,
			width: 249,
			height: 237,
			tuningTextColor: "#cecece",
			openStringColor: "#708aba",
			fretTextSize: 19,
			tuningLabelOffsetX: -4.41,
			tuningLabelFormat: "scientific",
			stringIndicatorOffsetX: 0.23,
			tuningTextSize: 14,
			tuningLabelOffsetY: -0.02,
			fretTextOffsetY: 0.15,
		},
	},
	{
		id: "custom-style",
		name: "A Minor (Custom Style)",
		description: "A Minor with custom colors and styling",
		props: {
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "x02210",
			},
			...BASE_CONFIG,
			width: 228,
			height: 228,
			fretColor: "#b7b2b2",
			stringColor: "#5b5a5a",
			backgroundColor: "#323232",
			tuningTextColor: "#555555",
			tuningTextSize: 20,
			tuningLabelOffsetX: 0.41,
			tuningLabelOffsetY: 0,
			tuningLabelFormat: "note-only",
			fretWidth: 41,
			stringWidth: 2.57,
			dotSize: 17,
			fretTextOffsetY: 0.33,
			dotColor: "#FF5733",
		},
	},
	{
		id: "high-position",
		name: "D Major (5th Fret)",
		description: "D barre chord at 5th fret position",
		props: {
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "x5777x",
			},
			...BASE_CONFIG,
		},
	},
	{
		id: "drop-d-tuning",
		name: "Drop D Tuning",
		description: "Chord in Drop D tuning",
		props: {
			instrument: {
				tuning: ["D2", "A2", "D3", "G3", "B3", "E4"],
				chord: "000232",
			},
			...BASE_CONFIG,
		},
	},
	{
		id: "open-strings",
		name: "E Minor (Open Strings)",
		description: "E Minor with open strings",
		props: {
			instrument: {
				tuning: ["E2", "A2", "D3", "G3", "B3", "E4"],
				chord: "022000",
			},
			...BASE_CONFIG,
		},
	},
	{
		id: "open-and-muted-strings",
		name: "C Major (Open & Muted)",
		description: "C Major with open and muted strings",
		props: {
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "x32010",
			},
			...BASE_CONFIG,
		},
	},
	{
		id: "custom-open-muted-style",
		name: "Custom Open/Muted Style",
		description: "Custom colors for open and muted strings",
		props: {
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "0x1xxx",
			},
			...BASE_CONFIG,
			openStringColor: "#7174bd",
			mutedStringColor: "#FF0000",
			width: 224,
			height: 215,
			stringWidth: 1.78,
			tuningTextColor: "#9a9999",
			tuningLabelOffsetY: -0.05,
			tuningLabelFormat: "note-only",
			stringIndicatorOffsetX: 0.06,
			stringIndicatorOffsetY: 0,
			fretTextOffsetX: -0.03,
			fretTextOffsetY: 0.47,
			nutStrokeWidth: 0.101,
			nutOffsetX: -0.07,
			nutOffsetY: -0.03,
			canvasOffsetX: -8,
			canvasOffsetY: -25,
			dotSize: 16,
		},
	},
	{
		id: "high-fret-notation",
		name: "High Fret Notation",
		description: "Chord using high fret numbers (10-12)",
		props: {
			instrument: {
				tuning: ["E2", "A2", "D3", "G3", "B3", "E4"],
				chord: "(10)(12)(12)(11)(10)(10)",
			},
			...BASE_CONFIG,
			width: 620,
			fretCount: 14,
		},
	},
	{
		id: "horizontal-right",
		name: "Horizontal Right View",
		description: "C Major in horizontal-right orientation",
		props: {
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "x32010",
			},
			...BASE_CONFIG,
			view: "horizontal-right",
		},
	},
	{
		id: "horizontal-left",
		name: "Horizontal Left View",
		description: "C Major in horizontal-left orientation",
		props: {
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "x32010",
			},
			...BASE_CONFIG,
			view: "horizontal-left",
		},
	},
	{
		id: "vertical-right",
		name: "Vertical Right View",
		description: "C Major in vertical-right orientation",
		props: {
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "x32010",
			},
			...BASE_CONFIG,
			view: "vertical-right",
			width: 207,
			height: 297,
			fretCount: 5,
			fretWidth: 23,
			fretHeight: 39,
			stringWidth: 1,
			dotSize: 14,
			dotTextSize: 12,
			fretTextSize: 12,
			tuningTextSize: 15,
			tuningTextColor: "#949393",
			tuningLabelOffsetX: 0.2,
			tuningLabelFormat: "note-only",
		},
	},
	{
		id: "vertical-left",
		name: "Vertical Left View",
		description: "C Major in vertical-left orientation",
		props: {
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "x32010",
			},
			...BASE_CONFIG,
			view: "vertical-left",
			width: 207,
			height: 297,
			fretCount: 5,
			fretWidth: 23,
			fretHeight: 39,
			stringWidth: 1,
			dotSize: 14,
			fretTextSize: 25,
			tuningTextSize: 12,
		},
	},
	{
		id: "performance-test",
		name: "Performance Test",
		description: "Optimized for performance testing",
		props: {
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "x32010",
			},
			...BASE_CONFIG,
			width: 255,
			height: 213,
			tuningLabelFormat: "note-only",
			fretWidth: 49,
			dotSize: 20,
			fontFamily: "monospace",
			dotTextSize: 16,
			validation: "strict",
			invalidBehavior: "keep-previous",
			fretTextColor: "#c6c6c6",
			tuningTextColor: "#b2b2b2",
			tuningLabelOffsetX: 0.25,
			tuningLabelOffsetY: -0.07,
			fretTextOffsetY: 0.31,
			canvasOffsetX: -12,
			canvasOffsetY: -23,
		},
	},
	{
		id: "tuning-label-offset-demo",
		name: "Tuning Label Offset",
		description: "Demonstrates tuning label offset customization",
		props: {
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "x32010",
			},
			...BASE_CONFIG,
			view: "horizontal-right",
			tuningLabelOffsetX: 0.8,
			width: 300,
			height: 200,
		},
	},
	{
		id: "tuning-label-format-demo",
		name: "Tuning Label Format",
		description: "Shows note-only format vs scientific notation",
		props: {
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "x32010",
			},
			...BASE_CONFIG,
			view: "vertical-right",
			tuningLabelFormat: "note-only",
			width: 200,
			height: 300,
		},
	},
	{
		id: "string-indicator-offset-demo",
		name: "String Indicator Offset",
		description: "Demonstrates O/X indicator positioning",
		props: {
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "x32010",
			},
			...BASE_CONFIG,
			view: "horizontal-right",
			stringIndicatorOffsetX: 0.3,
			width: 300,
			height: 200,
		},
	},
	{
		id: "combined-customizations",
		name: "Combined Customizations",
		description: "All 3 customization props together",
		props: {
			instrument: {
				tuning: ["E2", "A2", "D3", "G3", "B3", "E4"],
				chord: "x32010",
			},
			...BASE_CONFIG,
			view: "vertical-right",
			tuningLabelOffsetX: 0.3,
			tuningLabelFormat: "note-only",
			stringIndicatorOffsetX: 0.7,
			width: 220,
			height: 320,
			dotSize: 16,
			tuningTextSize: 16,
		},
	},
	{
		id: "nut-customization",
		name: "Nut Customization",
		description: "Custom nut styling with color and opacity",
		props: {
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "x32010",
			},
			...BASE_CONFIG,
			view: "horizontal-right",
			nutStrokeWidth: 0.2,
			nutColor: "#FF5733",
			nutOpacity: 0.8,
			width: 300,
			height: 250,
		},
	},
	{
		id: "canvas-positioning",
		name: "Canvas Positioning",
		description: "Demonstrates canvas offset for padding",
		props: {
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "x32010",
			},
			...BASE_CONFIG,
			canvasOffsetX: -9,
			canvasOffsetY: -7,
			backgroundColor: "#f0f0f0",
			tuningTextSize: 11,
			tuningLabelOffsetY: -0.02,
		},
	},
	{
		id: "combined-advanced-customization",
		name: "Advanced Customization",
		description: "All advanced features combined",
		props: {
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "133211",
			},
			...BASE_CONFIG,
			nutStrokeWidth: 0.15,
			nutColor: "#0066CC",
			nutOpacity: 0.9,
			canvasOffsetX: -12,
			canvasOffsetY: -9,
			barresOpacity: 0.7,
			dotColor: "#00AA66",
			barreColor: "#00AA66",
			width: 217,
			height: 226,
			tuningLabelOffsetX: 0.35,
			tuningLabelOffsetY: -0.11,
			tuningLabelFormat: "note-only",
			nutOffsetX: 0.08,
		},
	},
];
