/**
 * @fileoverview Preset configurations extracted from Storybook stories
 * @author svguitar-react
 * @version 1.0.0
 */

import type { Chord, ChordDiagramProps, Instrument, ViewId } from "../components/ChordDiagram/types";
import { DEFAULT_CHORD_STYLE } from "../components/ChordDiagram/constants";

export interface PresetConfig {
	id: string;
	name: string;
	description?: string;
	props: ChordDiagramProps;
}

// Base configuration with all defaults
const BASE_CONFIG = {
	...DEFAULT_CHORD_STYLE,
	tuningLabelOffsetX: 0.5,
	tuningLabelOffsetY: 0.5,
	tuningLabelFormat: "scientific" as const,
	stringIndicatorOffsetX: 0.5,
	stringIndicatorOffsetY: 0,
	barresWidth: 8,
	barresOpacity: 1,
	barresOffsetX: 0,
	barresOffsetY: 0,
	fretTextOffsetX: 0,
	fretTextOffsetY: 0,
	nutStrokeWidth: 0.075,
	nutOffsetX: 0,
	nutOffsetY: 0,
	nutOpacity: 1.0,
	nutColor: "#333333",
	canvasOffsetX: 0,
	canvasOffsetY: 0,
};

// Default tuning - same as used in all stories
const DEFAULT_TUNING = ["E2", "A2", "D3", "G3", "B3", "E4"];

export const CHORD_PRESETS: PresetConfig[] = [
	{
		id: "c-major-default",
		name: "C Major - Default",
		description: "C Major chord with default styling (Vertical Right)",
		props: {
			view: "vertical-right",
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "x32010",
			},
			width: 128,
			height: 219,
			canvasOffsetX: -39,
			canvasOffsetY: -19,
			fretCount: 5,
			stringCount: 6,
			fretWidth: 19,
			fretHeight: 35,
			stringWidth: 1,
			dotSize: 17,
			barreHeight: 9,
			backgroundColor: "#ffffff",
			fretColor: "#333333",
			stringColor: "#666666",
			dotColor: "#2196F3",
			dotTextColor: "#ffffff",
			barreColor: "#2196F3",
			fretTextColor: "#c6c6c6",
			tuningTextColor: "#e0e0e0",
			openStringColor: "#2196F3",
			mutedStringColor: "#DC143C",
			fontFamily: "monospace",
			dotTextSize: 11,
			fretTextSize: 11,
			tuningTextSize: 16,
			tuningLabelOffsetX: 0.01,
			tuningLabelOffsetY: 0.27,
			tuningLabelFormat: "note-only",
			stringIndicatorOffsetX: 0.58,
			stringIndicatorOffsetY: 0.63,
			barresWidth: 8,
			barresOpacity: 1,
			barresOffsetX: 0,
			barresOffsetY: -0.11,
			fretTextOffsetX: -0.13,
			fretTextOffsetY: 0.11,
			nutStrokeWidth: 0.075,
			nutOffsetX: 0,
			nutOffsetY: 0,
			nutOpacity: 1.0,
			nutColor: "#333333",
		},
	},
	{
		id: "f-major-horizontal-right",
		name: "F Major - Horizontal Right",
		description: "F Major chord with barre in horizontal layout",
		props: {
			view: "horizontal-right",
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "133211",
			},
			chord: {
				fingers: [],
				barres: [{ fret: 1, fromString: 1, toString: 6, text: "F" }],
			},
			width: 535,
			height: 214,
			fretCount: 5,
			stringCount: 6,
			fretWidth: 47,
			fretHeight: 30,
			stringWidth: 1,
			dotSize: 18,
			barreHeight: 19,
			backgroundColor: "#ffffff",
			fretColor: "#333333",
			stringColor: "#666666",
			dotColor: "#2196F3",
			dotTextColor: "#ffffff",
			barreColor: "#2196F3",
			fretTextColor: "#abaaaa",
			tuningTextColor: "#9e9a9a",
			openStringColor: "#2196F3",
			mutedStringColor: "#DC143C",
			fontFamily: "sans-serif",
			dotTextSize: 15,
			fretTextSize: 17,
			tuningTextSize: 17,
			tuningLabelOffsetX: 0.28,
			tuningLabelOffsetY: -0.04,
			tuningLabelFormat: "note-only",
			stringIndicatorOffsetX: 0.5,
			stringIndicatorOffsetY: 0,
			barresWidth: 12,
			barresOpacity: 1,
			barresOffsetX: 0.37,
			barresOffsetY: -0.14,
			fretTextOffsetX: 0,
			fretTextOffsetY: 0,
			nutStrokeWidth: 0.075,
			nutOffsetX: 0,
			nutOffsetY: 0,
			nutOpacity: 1.0,
			nutColor: "#333333",
			canvasOffsetX: 0,
			canvasOffsetY: 0,
		},
	},
	{
		id: "f-major-vertical-right",
		name: "F Major - Vertical Right",
		description: "F Major chord with barre in vertical layout",
		props: {
			view: "vertical-right",
			instrument: {
				tuning: DEFAULT_TUNING,
				chord: "133211",
			},
			chord: {
				fingers: [],
				barres: [{ fret: 1, fromString: 1, toString: 6, text: "F" }],
			},
			width: 192,
			height: 261,
			fretCount: 5,
			stringCount: 6,
			fretWidth: 23,
			fretHeight: 39,
			stringWidth: 1,
			dotSize: 18,
			barreHeight: 10,
			backgroundColor: "#ffffff",
			fretColor: "#333333",
			stringColor: "#666666",
			dotColor: "#2196F3",
			dotTextColor: "#ffffff",
			barreColor: "#2196F3",
			fretTextColor: "#d1d0d0",
			tuningTextColor: "#cecbcb",
			openStringColor: "#2196F3",
			mutedStringColor: "#DC143C",
			fontFamily: "sans-serif",
			dotTextSize: 15,
			fretTextSize: 17,
			tuningTextSize: 17,
			tuningLabelOffsetX: 0.04,
			tuningLabelOffsetY: 0.15,
			tuningLabelFormat: "note-only",
			stringIndicatorOffsetX: 0.35,
			stringIndicatorOffsetY: 0,
			barresWidth: 10,
			barresOpacity: 1,
			barresOffsetX: 0.12,
			barresOffsetY: 0.33,
			fretTextOffsetX: -6.32,
			fretTextOffsetY: 0.16,
			nutStrokeWidth: 0.075,
			nutOffsetX: 0,
			nutOffsetY: 0,
			nutOpacity: 1.0,
			nutColor: "#333333",
			canvasOffsetX: 0,
			canvasOffsetY: 0,
		},
	},
];
